### ISSUE TITLE
What is the query run on https://query.wikidata.org/ 

### ISSUE THREAD

**Issue by bnomis** [twitter-research/image-crop-analysis#1]
Your data notebook says:

"Save the output of the query run on https://query.wikidata.org/ as described in the paper with the name dataset.json"

But the paper does not accurately say what the query is.

Please provide the actual query. 

Thanks

**Comment by binaryaaron** [comment]
The full list of images used for our internal analysis were not Twitter's to share publicly for the purpose of full replication of our findings.  Rather, we delivered a sample query file that people can use to expanded to collect any data they wish to use to evaluate our research methodology.

The paper (Section 3.1, 1st paragraph) gives necessary and sufficient detail of what your custom query must look like so you can replicate the exact same logic.  The sample json file has a single image to demonstrate the required format to be used in the notebooks.  This can be expanded to include whichever URLs you wish to evaluate using our methodology.

**Comment by bnomis** [comment]
This issue is not asking for the list of images. It is asking for the SPARQL of the starting query - which could be a template with no identifying details.

You refer to a "sample query file": where is this? Sample input or output?

Section 3.1, 1st paragraph does not give "necessary and sufficient detail" to start a query. Why not give actual SPARQL which can be used as a starting point?
